### ISSUE TITLE
Using Authorization Policies

### ISSUE THREAD

**Issue by MarcusChamberlain** [ServiceComposer/ServiceComposer.AspNetCore.Mvc#53]
Hi there

At the moment we have an API Gateway using ServiceComposer. We wanted to add [Authorization Policies](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.0) to our routes, but since SC is intercepting the routes from MVC, there isn't a place to add our access policies.

Temporarily I had added an extra check alongside the "Matches" code like:

 ```
return HttpMethods.IsGet(httpVerb)
         && controller.ToLowerInvariant() == "products"
         && action.ToLowerInvariant() == "details"
         && routeData.Values.ContainsKey("id")
         && IsInValidRole(request);
```

While this does stop the route being accessed, SC works by returning a 404 if no routes match. If the route doesn't pass the authorization policy check, it would be preferable to return a 401. 

This also works rather crudely by comparing the roles directly, as opposed to being able to apply an Authorization Policy to the controller or individual route.

Any ideas on how this might apply to SC? Is this something that might be possible, or would it be considered outside the scope of the framework?

Cheers

**Comment by mauroservienti** [comment]
Hi @MarcusChamberlain, thanks for raising this. I have been thinking about this for a while. This is tricky, I tried the following:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddRouting();
    services.AddViewModelComposition();
    services.AddAuthorization(options =>
    {
        options.AddPolicy("APolicy", policy =>
            policy.Requirements.Add(new SamplePolicy()));
    });

    services.AddSingleton<IAuthorizationHandler, MySampleHandler>();
}

public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
{
    app.UseAuthorization();
    app.RunCompositionGateway( routeBuilder=> 
    {
        routeBuilder.MapComposableGet("{controller}/{id:int}");
    } );
}
```

but it miserably fails as the authorization infrastructure is not invoked when using Routing only as ServiceComposer does. I assumed that being authorization based on middlewares it would have worked. I read some of the Microsoft documentation about the topic, starting from the link you provided and all the samples are based on MVC Controllers which makes me think (I have no proof though) that the middleware is invoked only when MVC is used. I started diving into ASP.Net Core source on GitHub, and it seems to me the middleware (`AuthorizationMiddleware`) relies on endpoints to exist. So if the endpoint is defined it then combines the policy provider with `IAuthorizeData` provided by the endpoint. If there is no endpoint then there are authorization data (and thus no policies) resulting in a sort of "it's all good and authorized" kind of result.

As far as I have understood one option, and it's also my preferred one, would be to update ServiceComposer to .NET Core 3.x, change composition setup to use `IEndpointRouteBuilder` instead of `IRouteBuilder` to configure routing (which makes sense as endpoints are the new preferred way). 

I prefer this approach of using what Asp.Net Core provides instead of building something into ServiceComposer. (For the same reason I'm working on moving to attribute based routing the same way MVC does, the `Matches` thing makes little sense and it has a few drawbacks).

Thoughts?

**Comment by MarcusChamberlain** [comment]
> I read some of the Microsoft documentation about the topic, starting from the link you provided and all the samples are based on MVC Controllers which makes me think (I have no proof though) that the middleware is invoked only when MVC is used.

This was the same issue I ran into when researching this. I couldn't track down anything that .NET exposes outside of MVC that lets you manually hook into the routes and inject the policies needed. Quite surprising, but it seems to be more of a limitation of the .NET Core <2.2 routing pipeline than anything.

>As far as I have understood one option, and it's also my preferred one, would be to update ServiceComposer to .NET Core 3.x, change composition setup to use IEndpointRouteBuilder instead of IRouteBuilder to configure routing (which makes sense as endpoints are the new preferred way).

I'm hoping that since endpoints are supposed to make managing the route middleware easier, something for authorization policies would also pop up. I found one [article ](https://www.tpeczek.com/2019/01/aspnet-core-middleware-and-authorization.html) discussing this problem. The direction seemed to be that while you can't directly tap into the route/policy pipeline, you can make a new middleware that replicates it, which your routes then run through. 

That might be a lot for ServiceComposer to take on though.

**Comment by mauroservienti** [comment]
Thanks for the info @MarcusChamberlain, I'll have a look at the linked article. For my understanding what .NET Core version is your application targeting?

**Comment by MarcusChamberlain** [comment]
.NET Core 3.0

**Comment by mauroservienti** [comment]
Thanks. I raised https://github.com/ServiceComposer/ServiceComposer.AspNetCore/pull/75 which is a very simple change that enables endpoints to be used like in https://github.com/mauroservienti/designing-a-ui-for-microservices-demos/pull/255:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddRouting();
    services.AddViewModelComposition();
    services.AddAuthorization(options =>
    {
        options.AddPolicy("APolicy", policy =>
            policy.Requirements.Add(new SamplePolicy()));
    });

    services.AddSingleton<IAuthorizationHandler, SamplePolicyHandler>();
}

public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
{
    app.UseRouting();
    app.UseAuthorization();
    app.UseEndpoints(builder =>
    {
        builder.MapGet("{controller}/{id:int}", Composition.HandleRequest)
            .RequireAuthorization("APolicy");
    });
}
```

it's still missing something as there is strange error in case of authorization failure. I'll look into it next week.

**Comment by mauroservienti** [comment]
@MarcusChamberlain I just released 0.0.12 to Nuget. Can you please try and see if it solves the issue you're facing?

**Comment by MarcusChamberlain** [comment]
Thanks for the release @mauroservienti . It might be a few days before I get a chance to try it out (right into a busy new year!), but it looks just like what was needed. Cheers.

**Comment by mauroservienti** [comment]
Thanks @MarcusChamberlain, no rush. I'll close the issue for now, feel free to reopen or raise another one in case it's needed.
